const modules=[['overview','本周概览'],['resources','资源库'],['posts','开发日志'],['ai-lab','AI 实验室']];
const fallback={resources:[{title:'产品需求模板',type:'template',description:'跨职能协作的需求模板。',tags:['协作']},{title:'服务发布手册',type:'document',description:'从检查到回滚的标准流程。',tags:['工程']},{title:'知识库同步脚本',type:'code',description:'将内容同步到团队知识库。',tags:['自动化']}],posts:[{title:'从零搭建组织内容空间',summary:'内容沉淀应该服务于每天的协作节奏。',publishedAt:'2026-08-28'},{title:'我们如何用 Dify 做内部工具',summary:'一次从问题发现到上线验证的实验记录。',publishedAt:'2026-08-26'}],aiProducts:[{name:'Dify 工作流实验室',summary:'将内部知识和模型能力组合成可复用工作流。',url:'#',tags:['Dify','AI']} ]};
let layout={order:modules.map(([id])=>id),hidden:[],density:'comfortable',theme:'light'};
const get=async(path)=>{const r=await fetch('/api/v1'+path,{headers:{'X-User-ID':'00000000-0000-0000-0000-000000000001'}});if(!r.ok)throw Error();return r.json()};
async function data(){try{const d=await get('/dashboard');return {resources:d.resources||[],posts:d.posts||[],aiProducts:d.aiProducts||[]}}catch{return fallback}}
async function loadLayout(){try{return await get('/layout')}catch{return JSON.parse(localStorage.getItem('share-layout')||'null')||layout}}
function apply(){document.body.classList.toggle('dark',layout.theme==='dark');document.body.classList.toggle('compact',layout.density==='compact');layout.order.forEach(id=>document.querySelector('#'+id)?.parentElement.append(document.querySelector('#'+id)));modules.forEach(([id])=>document.querySelector('#'+id).hidden=layout.hidden.includes(id))}
function renderSettings(){const box=document.querySelector('#module-settings');box.innerHTML=layout.order.map((id,i)=>{const label=modules.find(x=>x[0]===id)[1];return `<div class="setting"><span>${label}</span><span><button data-move="${id}" data-d="-1" ${i===0?'disabled':''}>↑</button><button data-move="${id}" data-d="1" ${i===layout.order.length-1?'disabled':''}>↓</button><input data-hide="${id}" type="checkbox" ${layout.hidden.includes(id)?'':'checked'} aria-label="显示${label}"></span></div>`}).join('')}
function cards(d){document.querySelector('#resource-count').textContent=d.resources.length;document.querySelector('#post-count').textContent=d.posts.length;document.querySelector('#resource-list').innerHTML=d.resources.map(x=>`<article class="resource"><span class="tag">${x.type}</span><h3>${x.title}</h3><p>${x.description}</p></article>`).join('');document.querySelector('#post-list').innerHTML=d.posts.map(x=>`<article class="post"><small>${x.publishedAt?.slice(0,10)||'草稿'}</small><h3>${x.title}</h3><p>${x.summary}</p></article>`).join('');document.querySelector('#ai-list').innerHTML=d.aiProducts.map(x=>`<article class="ai-card"><span class="tag">${x.tags?.[0]||'AI'}</span><h3>${x.name}</h3><p>${x.summary}</p><a href="${x.url}">打开产品 →</a></article>`).join('')}
document.querySelector('#customize').onclick=()=>{renderSettings();document.querySelector('#density').value=layout.density;document.querySelector('#theme').value=layout.theme;document.querySelector('#drawer').showModal()};document.querySelector('#module-settings').onclick=e=>{const b=e.target;if(!b.dataset.move)return;const i=layout.order.indexOf(b.dataset.move),j=i+Number(b.dataset.d);[layout.order[i],layout.order[j]]=[layout.order[j],layout.order[i]];renderSettings()};document.querySelector('#module-settings').onchange=e=>{if(e.target.dataset.hide){const id=e.target.dataset.hide;layout.hidden=e.target.checked?layout.hidden.filter(x=>x!==id):[...layout.hidden,id]}};document.querySelector('#save-layout').onclick=async()=>{layout.density=document.querySelector('#density').value;layout.theme=document.querySelector('#theme').value;localStorage.setItem('share-layout',JSON.stringify(layout));try{await fetch('/api/v1/layout',{method:'PUT',headers:{'Content-Type':'application/json','X-User-ID':'00000000-0000-0000-0000-000000000001'},body:JSON.stringify(layout)})}catch{}apply()};
document.querySelector('#search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.resource,.post,.ai-card').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(q))};layout=await loadLayout();apply();cards(await data());
